name: Node Serial CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node-version: [6.x, 8.x, 10.x, 12.x, 14.x]
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # Checkout the npm/cli repo
    - uses: actions/checkout@v2

      # Installs the specific version of Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

      # Run the installer script
    - name: Install dependencies
      run: node . install

      # Run the tests
    - name: Run Tap tests
      run: node . run tap:serial -- "test/tap/*.js" -t600 -Rclassic -c
      env:
        DEPLOY_VERSION: testing

